from typing import Any, ClassVar, Dict

class BaseModel:
    model_fields: ClassVar[Dict[str, Any]]
    def __init__(self, **data: Any) -> None: ...
    @classmethod
    def model_validate(cls, obj: Any, *args: Any, **kwargs: Any) -> Any: ...

def Field(*args: Any, **kwargs: Any) -> Any: ...

class AliasChoices:
    def __init__(self, *args: str) -> None: ...
