from typing import Any, Optional

from requests import Response

class RequestException(Exception): ...

class HTTPError(RequestException):
    response: Optional[Response]
    def __init__(self, *args: Any, response: Optional[Response] = ..., **kwargs: Any) -> None: ...

class ConnectionError(RequestException): ...
class Timeout(RequestException): ...
