from typing import Any, Callable, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

def limits(*, calls: int, period: int) -> Callable[[F], F]: ...
def sleep_and_retry(func: F) -> F: ...

class RateLimitException(Exception): ...
