from typing import Any, Callable, TypeVar

F = TypeVar("F", bound=Callable[..., Any])

def retry(*, stop: Any, wait: Any, retry: Any) -> Callable[[F], F]: ...
def stop_after_attempt(attempt_number: int) -> Any: ...
def wait_random_exponential(*, max: int | float | None = ...) -> Any: ...
